name: Build & Test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build package
        run: pnpm build
